### ISSUE TITLE
Need rolling deployment

### ISSUE THREAD

**Issue by ericgreene** [ChrisMcKenzie/dropship#21]
This might be related to #18, but I'm not certain so I'm creating a new issue. An application accessing the API that is being updated receives 502s for a short period of time during deployments. Ideally, there would be rolling updates, and each instance could be removed from the load balancer during the update, and added back in as soon as it was completed.

**Comment by ChrisMcKenzie** [comment]
Yeah, this is exactly what #18 is talking about basically the way it works now is an update is not allowed to happen at the same exact moment but some update go so quickly that they can happen in the same second. so I plan making an option that allows users to say wait time.Duration before releasing the lock on consul/etcd. I am going to close this in favor of #18 as it has a bit more detail on how to implement.
