### ISSUE TITLE
Support for piping commands

### ISSUE THREAD

**Issue by mattwarren1234** [ChrisMcKenzie/dropship#28]
I have the following command in my dropship config file:
```
  before "script" {
    command = "ls | xargs echo"
  }
```
However, when I run it I get the following error:
```
2016/05/09 20:16:50 [INF]: Executing "script" hook with map[command:ls | xargs echo]
2016/05/09 20:16:50 [INFO]:
2016/05/09 20:16:50 [ERR]: Unable to execute "script" hook exit status 2
```
I'd like to be able to pipe commands in these scripts - is there a way to do that?

**Comment by mattwarren1234** [comment]
The parsing at https://github.com/ChrisMcKenzie/dropship/blob/master/dropship/hook_script.go could be updated to allow for piping...

**Comment by ChrisMcKenzie** [comment]
I think the way I should have done this is to wrap the command in `/bin/bash -c` so instead of the just executing the command we send it through an interpreter.

So on https://github.com/ChrisMcKenzie/dropship/blob/master/dropship/hook_script.go#L32:

instead of 
```
func executeCommand(c, cwd string) (string, error) {
	sCmd := strings.Fields(c)
	cmd := exec.Command(sCmd[0], sCmd[1:]...)
	if _, err := os.Stat(cwd); !os.IsNotExist(err) {
		cmd.Dir = cwd
	}
	out, err := cmd.Output()
	return string(out), err
}
```

it would be:
```
func executeCommand(c, cwd string) (string, error) {
	cmd := exec.Command("bash", "-c", c)
	if _, err := os.Stat(cwd); !os.IsNotExist(err) {
		cmd.Dir = cwd
	}
	out, err := cmd.Output()
	return string(out), err
}
```
This would allow better execution overall I think. I will flag this fix for the next release!

Thanks!

**Comment by mattwarren1234** [comment]
![image](https://cloud.githubusercontent.com/assets/6097694/15155074/b6ebf9d4-1695-11e6-9ed3-e26c1c7acb77.png)

**Comment by ChrisMcKenzie** [comment]
@mattwarren1234,

Just an update I have made the change we spoke about above, but still need to write some tests for it. I am super busy right now with house hunting so I am not sure when It will get released I will more than likely just release this and a couple other thing in a `1.5.3` patch release. 

Sorry for the slow turn around!

__cc:__ @ericgreene, @dewey4iv, @sdedelbrock
